# ================================================================
# Template Configuration File by FK 
# Delete or override values per project.
# ================================================================

# ------------------------------------------------
# 1. Experiment setup
# ------------------------------------------------
experiment_name: "m1"         # Name used for run folders/logs
base_run_dir: ./runs           # Base directory for experiment runs
# run_dir: "24h_30ep_v1"                   # Custom run dir (overrides auto naming)
train_dir: null                # Directory for saving training artifacts
img_log_dir: null              # Directory for saving image logs

seed: 42                     # Random seed (int)
device: "cuda:0"                   # "cpu", "mps", or "cuda:X"
num_workers: 16                # Data loader workers

# ------------------------------------------------
# 2. Data configuration
# ------------------------------------------------
data_dir: "../../data"       # Path to dataset
dataset:  "swisshourly"               # Dataset name # for example "swisshourly"

train_basin_file:       "../../data/basins_1.txt"      # File listing training basins
validation_basin_file:  "../../data/basins_1.txt"      # File listing validation basins
test_basin_file:        "../../data/basins_1.txt"      # File listing test basins

train_start_date:       2020-01-03   # first valid day of January
train_end_date:         2023-02-28   # last valid day of February
validation_start_date:  2023-03-01
validation_end_date:    2024-03-31
test_start_date:        2024-04-01
test_end_date:          2025-05-29                                      




dynamic_inputs:                  # name of your features in the dataset
- massa_blatten_hindcast
- null_values
- bruchji_prec
- blatten_prec
- blatten_temp
- blatten_ray
- eggishorn_temp
- eggishorn_ray
- bruchji_prec_6h
- blatten_prec_6h
- eggishorn_degreeday
- fc_bruchji_prec
- fc_blatten_prec
- fc_blatten_temp
- fc_eggishorn_temp
- fc_bruchji_prec_6h
- fc_blatten_prec_6h
- fc_eggishorn_degreeday
- hr 
- mo
# - blatten_temp_6h
# - blatten_ray_6h
# - eggishorn_temp_6h
# - eggishorn_ray_6h
# - fc_blatten_temp_6h
# - fc_eggishorn_temp_6h


# hindcasting/Forecasting inputs:
hindcast_inputs:           # (optional) features used during hindcast phase
- massa_blatten_hindcast
- bruchji_prec
- blatten_prec
- blatten_temp
- blatten_ray
- eggishorn_temp
- eggishorn_ray
- bruchji_prec_6h
- blatten_prec_6h
- eggishorn_degreeday
- hr
- mo
# - blatten_temp_6h
# - eggishorn_temp_6h
# - blatten_ray_6h
# - eggishorn_ray_6h



forecast_inputs:              # (optional) features used during forecast phase
- null_values
- fc_bruchji_prec
- fc_blatten_prec
- fc_blatten_temp
- blatten_ray
- fc_eggishorn_temp
- eggishorn_ray
- fc_bruchji_prec_6h
- fc_blatten_prec_6h
- fc_eggishorn_degreeday
- hr
- mo
# - fc_blatten_temp_6h
# - fc_eggishorn_temp_6h
# - blatten_ray_6h
# - eggishorn_ray_6h


forecast_seq_length: 24       # Must be < seq_length
forecast_overlap: null          # Must be <= forecast_seq_length
timestep_counter: true          # adds a feature that counts the time step in the sequence

# SH_addRollingFeatures: false
# SH_Rollings:
#   - feature: streamflow_hindcast
#     window_sizes: [3, 6, 12, 24]
#     operations: [mean, std, min, max]
#   - feature: prec_bruchji
#     window_sizes: [3, 6, 12, 24]
#     operations: [mean, std, min, max]
#   - feature: temp_binn
#     window_sizes: [3, 6, 12, 24]
#     operations: [mean, std, min, max]


# Target configuration
target_variables: 
  - massa_blatten
clip_targets_to_zero:
  - massa_blatten


# custom_normalization:
#   streamflow: 
#     scaling: "minmax"
#   streamflow_hindcast: 
#     scaling: "minmax"
  

# target_normalization: 
#   streamflow:
#     transform: "log"         # 'log' | 'none'
#     log_offset: 0.01         # offset for log
#     center: "mean"           # 'mean'|'median'|'none'
#     scale: "minmax"             # 'std'|'minmax'|'none'
  # streamflow_hindcast:
  #   transform: "log"         # 'log' | 'none'
  #   log_offset: 0.01         # offset for log
  #   center: "mean"           # 'mean'|'median'|'none'
  #   scale: "std"             # 'std'|'minmax'|'none'
# Whether to save transformed target/predictions additionally
# save_transformed_targets: false
# 
# lagged_features:               # Lagged input features
#   streamflow: [1]

# ------------------------------------------------
# 3. Model configuration
# ------------------------------------------------
model: "sequential_forecast_lstm"                    # Model type (e.g. "lstm", "transformer", "arlstm")
head: "regression"                     # Head type for output e.g. "regression", "gmm", "cmal", "umal"
hidden_size: 256              # Model hidden size (int or dict)

output_activation: "linear"
output_dropout: 0.1            #0.2–0.3 for multi-basin,  0.0–0.1 for single-basin

# LSTM
initial_forget_bias: 2.5                    # Initial bias value of the forget gate (0-3, high helps the model remember the past)

# Embedding specifications (dicts)
# define embedding network for dynamic inputs
# dynamics_embedding: null
#   type: fc
#   hiddens:                                # define number of neurons per layer in the FC network used as embedding network
#     - 16
#     - 32
#     - 128
#   activation: Relu                        # activation function of embedding network
#   dropout: 0.0                            # dropout applied to embedding network

# statics_embedding: null

# Auto-Regressive LSTM
# autoregressive_inputs:          # Must match lagged version of target
#   - streamflow_shift1       

# ------------------------------------------------
# 4. Training configuration
# ------------------------------------------------
epochs: 1000
max_updates_per_epoch: null   # Limits number of training updates per epoch (for debugging) [int or null]

batch_size: 64
optimizer: "AdamW"             # specify optimizer [Adam. AdamW]
loss: nse                     # specify loss [MSE, NSE, RMSE]

# regularization:
#   - ["l2", 1e-5]             # weight decay

learning_rate:  1e-3         # specify learning rates to use starting at specific epochs (0 is the initial learning rate)
clip_gradient_norm: 3.0           # avoids exploding gradients


seq_length: 360  # 2 weeks of context, predict last day of sequence               # Input sequence length (in frequency of measure -> if hourly: 168 is 2weeks, 8760 is a year)
predict_last_n: 24            # Prediction horizon (will consider only the t0+predict_last_n*freq_measure point)

metrics:
- MAPE
- NSE
- MSE
- RMSE

# Early stopping / Dynamic learning rate
validate_every: 1                     # specify after how many epochs to perform validation 
validate_n_random_basins: 1

# NEED validate_every set to 1
early_stopping: true
patience_early_stopping: 10
minimum_epochs_before_early_stopping: 20
min_delta_early_stopping: 5e-7
# Dynamic LR
dynamic_learning_rate: true
patience_dynamic_learning_rate: 5
factor_dynamic_learning_rate: 0.6

# ------------------------------------------------
# 5. Output & Logging
# ------------------------------------------------
log_interval: 10
log_n_figures: 1
log_tensorboard: true

save_train_data: false
save_validation_results: false
save_all_output: false
save_weights_every: 10

save_git_diff: false
verbose: 1                      # 0 = logs only, 1 = logs + progress

# ------------------------------------------------
# 6. Advanced options
# ------------------------------------------------
# Handling missing data
nan_handling_method: masked_mean       # e.g. "mask", "zero"
nan_step_probability: 0.0
nan_sequence_probability: 0.0
nan_handling_pos_encoding_size: 0
