# ------------------------------------------------
# 1. Experiment setup
# ------------------------------------------------

experiment_name: "test_plot"         # Name used for run folders/logs
base_run_dir: ./runs           # Base directory for experiment runs

train_dir: null                # Directory for saving training artifacts
img_log_dir: null              # Directory for saving image logs

seed: 42                     # Random seed (int)
device: "cuda:0"                   # "cpu", "mps", or "cuda:X"
num_workers: 16                # Data loader workers

# ------------------------------------------------
# 2. Data configuration
# ------------------------------------------------

data_dir: "../data"       # Path to dataset
dataset:  "swisshourly"               # Dataset name # for example "swisshourly"

train_basin_file:       "../data/Data_RS.txt"      # File listing training basins
validation_basin_file:  "../data/Data_RS.txt"      # File listing validation basins
test_basin_file:        "../data/Data_RS.txt"      # File listing test basins

train_start_date:       1983-03-04   # first valid day of January
train_end_date:         2021-04-30   # last valid day of February
validation_start_date:  2021-03-01
validation_end_date:    2023-02-02
test_start_date:        2023-02-03
test_end_date:          2024-02-04                                      


dynamic_inputs:                 
- streamflow_hindcast
- null_values
- Massa|22_Q simule
- Massa|69_i
- Massa|69_T
- Massa|70_h
- Massa|71_h
- Massa|71_A
- Massa|73_H
- Massa|73_A
- HourOfDaySinus
- DayOfYearSinus


hindcast_inputs:
- streamflow_hindcast
- Massa|22_Q simule
- Massa|69_i
- Massa|69_T
- Massa|70_h
- Massa|71_h
- Massa|71_A
- Massa|73_H
- Massa|73_A
- HourOfDaySinus
- DayOfYearSinus

forecast_inputs:
- null_values
- Massa|22_Q simule
- Massa|69_i
- Massa|69_T
- Massa|70_h
- Massa|71_h
- Massa|71_A
- Massa|73_H
- Massa|73_A
- HourOfDaySinus
- DayOfYearSinus


forecast_seq_length: 24         # Must be < seq_length
forecast_overlap: null          # Must be <= forecast_seq_length
timestep_counter: true          # adds a feature that counts the time step in the sequence

# -- TARGET FEATURES: --
target_variables: 
  - streamflow
clip_targets_to_zero:
  - streamflow

# custom_normalization:
#   streamflow: 
#     scaling: "minmax"
#   streamflow_hindcast: 
#     scaling: "minmax"
  

# target_normalization: 
#   streamflow:
#     transform: "log"         # 'log' | 'none'
#     log_offset: 0.01         # offset for log
#     center: "mean"           # 'mean'|'median'|'none'
#     scale: "minmax"             # 'std'|'minmax'|'none'
#   streamflow_hindcast:
#     transform: "log"         # 'log' | 'none'
#     log_offset: 0.01         # offset for log
#     center: "mean"           # 'mean'|'median'|'none'
#     scale: "std"             # 'std'|'minmax'|'none'

# Whether to save transformed target/predictions additionally
# save_transformed_targets: false
# -------------------

# ------------------------------------------------
# 3. Model configuration
# ------------------------------------------------

model: "sequential_forecast_lstm"                    # Model type (e.g. "lstm", "transformer", "arlstm")
head: "regression"                     # Head type for output e.g. "regression", "gmm", "cmal", "umal"
hidden_size: 128              # Model hidden size (int or dict)
num_layers: 1                # Number of LSTM layers

seq_length: 60  # 2 weeks of context, predict last day of sequence               # Input sequence length (in frequency of measure -> if hourly: 168 is 2weeks, 8760 is a year)
predict_last_n: 24            # Prediction horizon (will consider only the t0+predict_last_n*freq_measure point)

output_activation: "linear"
output_dropout: 0.05            #0.2–0.3 for multi-basin,  0.0–0.1 for single-basin
# LSTM
initial_forget_bias: 2                   # Initial bias value of the forget gate (0-3, high helps the model remember the past)

# ------------------------------------------------
# 4. Training configuration
# ------------------------------------------------

epochs: 1000
learning_rate:  1e-3         # specify learning rates to use starting at specific epochs (0 is the initial learning rate)

# dynamics_embedding:
#   type:
#     fc
#   hiddens:
#     [16]
#   activation:
#     relu
#   dropout:
#     0.0

batch_size: 256
optimizer: "AdamW"             # specify optimizer [Adam. AdamW]

custom_loss:
  losses:
  - smape
  - mse
  - nse
  weights:
  - 0.8
  - 0.1
  - 0.1

# custom_loss or smape
loss: custom_loss                     # specify loss [MSE, NSE, RMSE]
clip_gradient_norm: 3.0           # avoids exploding gradients

metrics:
- MAPE
- NSE
- MSE
- RMSE

# Early stopping / Dynamic learning rate
validate_every: 1                     # specify after how many epochs to perform validation 
validate_n_random_basins: 1

# NEED validate_every set to 1
early_stopping: true
patience_early_stopping: 20
minimum_epochs_before_early_stopping: 20
min_delta_early_stopping: 5e-7
# Dynamic LR
dynamic_learning_rate: true
patience_dynamic_learning_rate: 5 #6
factor_dynamic_learning_rate: 0.4

save_best_enabled: true
save_best_criterion: val_loss  # or sum_metrics
# ------------------------------------------------
# 5. Output & Logging
# ------------------------------------------------

log_interval: 10
log_n_figures: 1
log_tensorboard: true

save_train_data: false
save_validation_results: false
save_all_output: false
save_weights_every: 5

verbose: 1                      # 0 = logs only, 1 = logs + progress

# ------------------------------------------------
# 6. Advanced options
# ------------------------------------------------

# Handling missing data
nan_handling_method: masked_mean       # e.g. "mask", "zero"
nan_step_probability: 0.0
nan_sequence_probability: 0.0
nan_handling_pos_encoding_size: 0
