xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    day:
      dims: []
      attrs: {}
      data: 0.3551357388496399
    prec_bruchji:
      dims: []
      attrs: {}
      data: 0.45603853464126587
    rad_visp:
      dims: []
      attrs: {}
      data: 267.30609130859375
    streamflow:
      dims: []
      attrs: {}
      data: 21.968379974365234
    streamflow_shift1:
      dims: []
      attrs: {}
      data: 21.968463897705078
    temp_binn:
      dims: []
      attrs: {}
      data: 7.851250171661377
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    day:
      dims: []
      attrs: {}
      data: 0.4906025230884552
    prec_bruchji:
      dims: []
      attrs: {}
      data: 0.11297500878572464
    rad_visp:
      dims: []
      attrs: {}
      data: 168.31658935546875
    streamflow:
      dims: []
      attrs: {}
      data: 16.338645935058594
    streamflow_shift1:
      dims: []
      attrs: {}
      data: 16.33889389038086
    temp_binn:
      dims: []
      attrs: {}
      data: 6.293473720550537
